language: php
php:
  - 5.6
  - 7.0

install:
  - composer install --prefer-dist --no-interaction --dev

script:
  - vendor/bin/phpspec -c=phpspec-ci.yml run

after_script:
  - travis_retry vendor/bin/coveralls